/* ---------- ACOG-sourced education content ----------
   Fetched from the live ACOG patient FAQ pages listed in `sources` below
   and condensed into `excerpt` (kept close to ACOG's own wording, numbers
   preserved exactly). This is the single source of truth for both the
   patient-facing Education tab (src/App.jsx) and the /api/ask-education
   grounding prompt — the model is told to answer from `excerpt` first
   rather than its own general knowledge.
------------------------------------------------------------------------- */
export const ACOG_CONTENT = {
  nutrition: {
    label: "Nutrition",
    scope: "nutrition, diet, and supplements during pregnancy and postpartum",
    sources: [
      { label: "ACOG – Healthy Eating During Pregnancy (FAQ001)", url: "https://www.acog.org/womens-health/faqs/healthy-eating-during-pregnancy" },
      { label: "ACOG – Breastfeeding Your Baby (FAQ029)", url: "https://www.acog.org/womens-health/faqs/breastfeeding-your-baby" },
    ],
    excerpt: `"Eat for two" does not mean eating twice as much food — it means eating twice as healthy. Key daily targets during pregnancy: folic acid 600 mcg (take a prenatal vitamin with at least 400 mcg starting at least 1 month before pregnancy and through the first 12 weeks; 4 mg/day if you've previously had a child with a neural tube defect); iron 27 mg (up from 18 mg when not pregnant) — pair iron-rich foods (beans, lentils, iron-fortified cereal, beef, turkey, liver, shrimp) with vitamin C (oranges, grapefruit, strawberries, broccoli, peppers) to help absorption; calcium 1,000 mg (1,300 mg for ages 14-18); vitamin D 600 IU; choline 450 mg — not in most prenatal vitamins, so get it from chicken, beef, eggs, milk, soy, or peanuts; vitamin C 85 mg (80 mg under age 19). Eat 2-3 servings (4 oz each) of fish/shellfish per week for omega-3s, but avoid bigeye tuna, king mackerel, marlin, orange roughy, shark, swordfish, and tilefish, and limit albacore tuna to 6 oz/week; avoid raw fish and shellfish. Drink 8-12 cups of water a day. Do not exceed the recommended prenatal vitamin dose — some ingredients (like vitamin A) can cause birth defects at higher doses; supplements are not FDA-regulated, so choose reputable brands and ask your ob-gyn or a dietitian for recommendations. While breastfeeding: about 450-500 extra calories/day (roughly 2,500 total if your weight is in the normal range), continue your prenatal vitamin, and caffeine up to about 200 mg/day is generally fine.`,
    faqs: [
      { q: "Do I need to “eat for two” during pregnancy?", a: "No — the saying doesn't mean eating twice as much food, it means eating twice as healthy. Focus on nutrient-dense foods from the five food groups rather than doubling portions." },
      { q: "How much folic acid do I need, and why?", a: "600 micrograms a day during pregnancy. Since that's hard to get from food alone, take a daily prenatal vitamin with at least 400 mcg of folic acid, ideally starting a month before pregnancy and through the first 12 weeks — it helps prevent neural tube birth defects of the brain and spine." },
      { q: "How much iron and calcium do I need?", a: "27 mg of iron a day (up from 18 mg when not pregnant) — pair iron-rich foods like beans, lentils, and lean meat with vitamin C to help absorption. For calcium, it's 1,000 mg a day (1,300 mg if you're 14-18), from dairy, fortified foods, or dark leafy greens." },
      { q: "Which fish should I avoid, and how much can I eat?", a: "Avoid bigeye tuna, king mackerel, marlin, orange roughy, shark, swordfish, and tilefish. Limit albacore (white) tuna to 6 oz a week. Otherwise, 2-3 servings (4 oz each) of lower-mercury fish a week is recommended for the omega-3s. Skip raw fish and shellfish." },
      { q: "Can I take extra prenatal vitamins if I'm told I have a deficiency?", a: "No — don't take more than the recommended amount on your own. Some ingredients, like vitamin A, can cause birth defects at higher doses. If you need more of something, your ob-gyn will usually recommend it as a separate, specific supplement." },
    ],
  },

  hypertension: {
    label: "Hypertension",
    scope: "blood pressure, gestational hypertension, and pre-eclampsia during pregnancy and postpartum",
    sources: [
      { label: "ACOG – Preeclampsia and High Blood Pressure During Pregnancy (FAQ034)", url: "https://www.acog.org/womens-health/faqs/preeclampsia-and-high-blood-pressure-during-pregnancy" },
    ],
    excerpt: `Blood pressure guidelines: normal is less than 120/80 mm Hg; elevated is systolic 120-129 with diastolic under 80; Stage 1 hypertension is systolic 130-139 or diastolic 80-89; Stage 2 hypertension is systolic at least 140 or diastolic at least 90. Chronic hypertension means high blood pressure that existed before pregnancy or was diagnosed before 20 weeks. Gestational hypertension means a systolic reading of 140+ and/or diastolic of 90+ that first appears after 20 weeks in someone with previously normal blood pressure; most people have only a small increase, but some develop severe hypertension (systolic 160+ and/or diastolic 110+), which carries risk of serious complications. Preeclampsia is a serious disorder that can affect all the organs, usually developing after 20 weeks (often the third trimester) but it can also appear in the weeks after childbirth; before 34 weeks it's called early-onset. Symptoms include swelling of the face or hands, a headache that won't go away, seeing spots or changes in eyesight, pain in the upper abdomen or shoulder, nausea/vomiting in the second half of pregnancy, sudden weight gain, and difficulty breathing — call your ob-gyn right away if these appear. "Severe features" include a low platelet count, abnormal kidney or liver function, upper abdominal pain, vision changes, fluid in the lungs, a severe headache, or a systolic reading of 160+/diastolic of 110+. HELLP syndrome (hemolysis, elevated liver enzymes, low platelets) is a medical emergency. Risk factors include a past pregnancy with preeclampsia, carrying more than one fetus, chronic hypertension, kidney disease, diabetes, autoimmune conditions like lupus, first pregnancy, BMI over 30, family history, age 35+, and prior pregnancy complications. Low-dose aspirin may be recommended for those at high risk or with two or more moderate risk factors — only start it after talking with your ob-gyn.`,
    faqs: [
      { q: "What do the blood pressure numbers actually mean?", a: "Normal is under 120/80 mm Hg. Elevated is 120-129 systolic with diastolic under 80. Stage 1 hypertension is 130-139 systolic or 80-89 diastolic. Stage 2 hypertension is 140+ systolic or 90+ diastolic." },
      { q: "What's the difference between gestational hypertension and preeclampsia?", a: "Gestational hypertension is a blood pressure of 140/90 or higher that first shows up after 20 weeks in someone whose blood pressure was previously normal. Preeclampsia is a more serious disorder that can affect organs throughout the body — it may include high blood pressure plus signs like protein in the urine, abnormal liver/kidney function, or low platelets." },
      { q: "What symptoms should make me call my ob-gyn right away?", a: "Swelling of the face or hands, a headache that won't go away, seeing spots or vision changes, pain in the upper abdomen or shoulder, nausea or vomiting in the second half of pregnancy, sudden weight gain, or difficulty breathing." },
      { q: "What counts as a hypertensive emergency?", a: "A systolic reading of 160 mm Hg or higher, or a diastolic reading of 110 mm Hg or higher — this is considered severe and needs immediate medical attention, along with any of the “severe features” like a bad headache, vision changes, or upper abdominal pain." },
      { q: "Can anything help prevent preeclampsia?", a: "Prevention starts with knowing your risk factors. Your ob-gyn may recommend low-dose aspirin if you're at high risk, or if you have two or more moderate risk factors — don't start aspirin on your own without talking to them first." },
    ],
  },

  "postpartum-recovery": {
    label: "Postpartum Recovery",
    scope: "general postpartum physical recovery: bleeding/lochia, incision or perineal healing, mood changes, and recovery timelines (not pelvic floor/exercise specifics and not breastfeeding specifics)",
    sources: [
      { label: "ACOG – Postpartum Pain Management (FAQ519)", url: "https://www.acog.org/womens-health/faqs/postpartum-pain-management" },
    ],
    excerpt: `Common postpartum symptoms include vaginal bleeding, cramping ("afterpains" as the uterus shrinks back down), pain in the back, neck, or joints, perineal pain, incision pain after a cesarean birth, swollen breasts, bladder or bowel problems, and hemorrhoids — how long these last varies a lot from person to person, from a few days to several weeks. Call 911 or seek emergency help right away if you have chest pain; are coughing or gasping for air; have seizures; have thoughts of hurting yourself or your baby; have severe pain in your lower abdomen; or have pain, swelling, and tenderness in your legs. Call your ob-gyn right away if you have a headache that doesn't get better with medicine, or a bad headache with vision changes; a fever over 100.4°F; persistent nausea and vomiting; pain or burning during urination that is severe or continues more than a few days after delivery; heavy bleeding (soaking through two pads an hour for more than an hour or two); red streaks or painful new lumps in your breasts; pain that doesn't improve or gets worse from an episiotomy, tear, or incision; redness or discharge from an episiotomy, tear, or incision; foul-smelling vaginal discharge; or feelings of hopelessness lasting more than 10 days after delivery. For pain relief, ibuprofen is usually preferred while breastfeeding since little passes into breast milk, and acetaminophen is also considered safe; a heating pad helps with afterpains and back/neck pain; ice packs and witch hazel help perineal pain in the first 24-72 hours, followed by warm sitz baths afterward.`,
    faqs: [
      { q: "How much postpartum bleeding and pain is normal?", a: "Vaginal bleeding, cramping (afterpains), perineal or incision pain, swollen breasts, and bladder/bowel changes are all common and can last from a few days to several weeks depending on the symptom and the person." },
      { q: "What should send me straight to the ER, not just a call to my ob-gyn?", a: "Chest pain; coughing or gasping for air; seizures; thoughts of hurting yourself or your baby; severe lower abdominal pain; or pain, swelling, and tenderness in your leg. Call 911 or go to the ER for any of these." },
      { q: "What symptoms mean I should call my ob-gyn right away (but it's not a 911 emergency)?", a: "A headache that won't improve with medicine (or one with vision changes), a fever over 100.4°F, persistent nausea/vomiting, severe or prolonged burning with urination, soaking through two pads an hour for more than an hour or two, red streaks or painful lumps in your breast, worsening incision/tear pain or discharge, foul-smelling discharge, or feeling hopeless for more than 10 days." },
      { q: "What pain relievers are safe while breastfeeding?", a: "Ibuprofen is usually the preferred first choice since very little passes into breast milk. Acetaminophen is also considered safe. Talk to your ob-gyn before combining medications or if you think you need something stronger." },
      { q: "Is it normal to feel very emotional after birth?", a: "\"Baby blues\" — mood swings and tearfulness in the first couple of weeks — are common and usually pass on their own. Feelings of hopelessness that last more than 10 days are a reason to call your ob-gyn right away, since postpartum depression is common and treatable." },
    ],
  },

  "pelvic-floor": {
    label: "Pelvic Floor & Physical Recovery",
    scope: "pelvic floor health and physical/musculoskeletal recovery after pregnancy: Kegel exercises, diastasis recti, returning to exercise, incontinence, and pelvic organ prolapse",
    sources: [
      { label: "ACOG – Pelvic Support Problems (FAQ012)", url: "https://www.acog.org/womens-health/faqs/pelvic-support-problems" },
      { label: "ACOG – Exercise After Pregnancy (FAQ131)", url: "https://www.acog.org/womens-health/faqs/exercise-after-pregnancy" },
    ],
    excerpt: `Pelvic organ prolapse (POP) happens when the muscles and connective tissue of the pelvic floor can no longer fully support the vagina, uterus, bladder, or rectum, and they drop down — the main cause is pregnancy and vaginal childbirth, which can weaken the pelvic floor. Symptoms can include a feeling of pelvic pressure or fullness, organs bulging from the vagina, urine leakage, trouble fully emptying the bladder, problems having a bowel movement, and lower back pain — many people have no symptoms at all and don't need treatment; a care team simply monitors it at regular checkups. Kegel (pelvic floor) exercises: squeeze the muscles you'd use to stop the flow of urine, hold for 3 seconds, then relax for 3 seconds; do 10 contractions, three times a day; gradually work up to 10-second holds; don't hold your breath or squeeze your stomach, thigh, or buttock muscles instead. Doing these regularly may improve incontinence and slow the progression of prolapse. On exercise after pregnancy: after a healthy vaginal delivery, it's usually safe to start light exercise within a few days after birth, or as soon as you feel ready; after a cesarean birth or complications, ask your ob-gyn when it's safe to begin. The general target is at least 150 minutes a week of moderate-intensity aerobic activity (for example, five 30-minute sessions, or shorter sessions spread through the day), plus muscle-strengthening activities — including Kegels — on at least 2 days a week. Stop exercising if you feel pain. Benefits include help with mood, energy, sleep, and losing pregnancy weight, and exercise may help prevent postpartum depression.`,
    faqs: [
      { q: "When can I start pelvic floor exercises (Kegels)?", a: "There's no need to wait — you can start any time after birth, even the immediate postpartum period, if it's comfortable. Squeeze the muscles you'd use to stop urine flow, hold 3 seconds, relax 3 seconds, and repeat for 10 contractions, three times a day, gradually working up to 10-second holds." },
      { q: "What is pelvic organ prolapse?", a: "It's when weakened pelvic floor muscles and tissue — most often from pregnancy and vaginal childbirth — can no longer fully support the vagina, uterus, bladder, or rectum, causing them to drop. Symptoms include pelvic pressure or fullness, a bulge, urine leakage, or trouble fully emptying the bladder. Many people have no symptoms and need no treatment, just monitoring." },
      { q: "When is it safe to exercise again after delivery?", a: "After an uncomplicated vaginal delivery, light exercise is usually fine within a few days, or as soon as you feel ready. After a C-section or any complications, check with your ob-gyn first about timing." },
      { q: "How much exercise should I aim for postpartum?", a: "At least 150 minutes a week of moderate-intensity aerobic activity (like five 30-minute walks, or shorter chunks through the day), plus muscle-strengthening work — including Kegels — on at least 2 days a week. Stop if you feel pain." },
      { q: "Is it normal to leak urine after having a baby?", a: "Mild urine leakage (stress incontinence) is common postpartum. Pelvic floor (Kegel) exercises often help, and it's worth mentioning to your care team rather than assuming you have to live with it — there are effective treatments beyond exercise too." },
    ],
  },

  breastfeeding: {
    label: "Breastfeeding Support",
    scope: "breastfeeding and lactation: latch, milk supply, mastitis, pumping, and medication safety while breastfeeding",
    sources: [
      { label: "ACOG – Breastfeeding Your Baby (FAQ029)", url: "https://www.acog.org/womens-health/faqs/breastfeeding-your-baby" },
    ],
    excerpt: `Exclusive breastfeeding is recommended for the first 6 months of life; continuing for 2 years or more (alongside other foods) gives the most benefits, but any amount of breastfeeding helps, including lowering the baby's risk of SIDS. Most healthy newborns are ready to breastfeed within the first hour after birth, and skin-to-skin contact right after birth helps encourage this. Feed on demand rather than a strict schedule — most newborns feed at least 8-12 times in 24 hours (about every 2-3 hours), often 10-15 minutes per breast, though patterns vary a lot, including much longer feeds or frequent "cluster feeding." Hunger cues include looking alert, bending the arms, closing the fists, and bringing fingers to the mouth — crying is a late sign of hunger. On diet while breastfeeding: your body needs about 450-500 extra calories a day (roughly 2,500 total if your weight is in the normal range); eat fish/seafood 2-3 times a week but avoid high-mercury fish (bigeye tuna, king mackerel, marlin, orange roughy, shark, swordfish, tilefish) and limit albacore tuna to 6 oz a week; continue your prenatal multivitamin if your ob-gyn recommends it; drink plenty of fluids. Caffeine up to about 200 mg a day most likely won't affect the baby. If you want an occasional alcoholic drink, wait at least 2 hours after a single drink before breastfeeding — there's no need to "pump and dump." Most medications are safe while breastfeeding, since levels that reach the baby are usually much lower than in your own bloodstream — check with your care team or the LactMed database for a specific medication. Engorgement (breasts feeling very full, hard, and tender as milk comes in) usually improves with more frequent feeding and cold packs; red streaks or painful new lumps can signal mastitis and need prompt care-team attention.`,
    faqs: [
      { q: "How often and how long should I breastfeed?", a: "Let your baby set the schedule rather than a strict clock. Most newborns feed at least 8-12 times in 24 hours (roughly every 2-3 hours), often 10-15 minutes per breast — though longer feeds and frequent \"cluster feeding\" are also normal." },
      { q: "What should I know about my diet while breastfeeding?", a: "You need about 450-500 extra calories a day. Keep taking your prenatal vitamin if recommended, eat fish 2-3 times a week but avoid high-mercury fish (like shark, swordfish, and king mackerel), and drink plenty of fluids." },
      { q: "Can I have caffeine or alcohol while breastfeeding?", a: "Caffeine up to about 200 mg a day most likely won't affect your baby. For alcohol, wait at least 2 hours after a single drink before breastfeeding — there's no need to pump and discard your milk in the meantime." },
      { q: "What are signs of mastitis or engorgement I should watch for?", a: "Engorgement — full, hard, tender breasts as milk comes in — is common and usually eases with frequent feeding and cold packs. Red streaks or a painful new lump can signal mastitis and needs prompt attention from your care team." },
      { q: "Can I breastfeed while taking medication?", a: "Most medications are safe, since the amount that reaches your baby through milk is usually much lower than the level in your own bloodstream. Still, check a specific medication with your care team or the LactMed database before starting or stopping anything." },
    ],
  },
};
